-- Enables geographic distance calculations via the earthdistance extension.
-- cube is earthdistance's required dependency; both ship with postgresql-contrib.
-- NOTE: cube and earthdistance extensions are created by postgres-init container.
